### ISSUE TITLE
conflict with pmi?

### ISSUE THREAD

**Issue by ysagon** [hpc2n/spank-private-tmp#1]
Hello,

I'm trying your plugin, which seems very interesting. It works fine if I mount something like /scratch,
but I mount as well /tmp, I have a problem when I submit a mpi job.

```
run: error: mpi/pmi2: failed to send temp kvs to compute nodes
```

Do you have this problem as well? I'm using Slurm 14.11.4 with pmi

**Comment by kmjonsson** [comment]
Hi!

No we don't have that problem. What mpi (type and version) are you using?

Can you show me how your plugstack.conf looks like?

**Comment by ysagon** [comment]
I'm using openmpi 1.8.4 compiled with gcc 4.4.7 and pmi2

working:

```
required        hpc2n-tmpdir.so base=/tmpslurm/ mount=/scratch
```

not working:

```
required        hpc2n-tmpdir.so base=/tmpslurm/ mount=/scratch mount=/tmp
```

I'm as well using `use-env`  which do that and is loaded before `hpc2n-tmpdir`:

```
TMPDIR="/scratch"
```

**Comment by ysagon** [comment]
Do you have any clue?

**Comment by kmjonsson** [comment]
Sorry for late answer. Totally missed your question. 

We are running the PMI included in slurm and also PMIX with the plugin without any problem.

**Comment by ysagon** [comment]
Thanks for the follow up! It's working now:) But I don't remember what was the issue, sorry. I close the issue.
