### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by paran1** [hpc2n/spank-private-tmp#2]
The source code is missing licensing notices. https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html#SEC4

The LICENSE file also have some minor whitespace diffs compared to https://www.gnu.org/licenses/old-licenses/lgpl-2.0.txt (/usr/share/common-licenses/LGPL-2 on ubuntu systems), I suggest reverting those.

**Comment by paran1** [comment]
Another strange thing is that github lists the repository as LGPL-2.1 instead of 2.0. How does that even get set, some sort of autodetection? If I remember correctly, the biggest change in LGPL 2.1 is the L in the name changes from "Library" to "Lesser".

And of course I notice this now, not earlier today when I created the issue. :-)

**Comment by kmjonsson** [comment]
Fixed
