### ISSUE TITLE
conflict with sbcast

### ISSUE THREAD

**Issue by LaHaine** [hpc2n/spank-private-tmp#4]
I've used this plugin to create a private /scratch on every node. But I cannot broadcast files to this directory using sbcast:
````
% sbcast /tmp/test /scratch/test
sbcast: error: REQUEST_FILE_BCAST(pax9-01): Permission denied
sbcast: error: REQUEST_FILE_BCAST(pax9-02): Permission denied
sbcast: error: REQUEST_FILE_BCAST(pax9-03): Permission denied
sbcast: error: REQUEST_FILE_BCAST(pax9-00): Permission denied
````
I have to use the real directory for sbcast.

**Comment by kmjonsson** [comment]
Yes this is a known feature.

Last time I checked I don't think it's possible to get sbcast into the private /scratch due to how it's implemented in Slurm.
