### ISSUE TITLE
Use slurm_spank_log instead of slurm_error  for slurm_spank_job_prolog

### ISSUE THREAD

**Issue by ysagon** [hpc2n/spank-private-tmp#5]
Hi,

If I  understand well, the plugin prints

```
error: private-tmpdir: slurm_spamk_job_prolog
```
at each startup. (typo: spank vs spamk). Is there a reason to use slurm_errror for informative messages?

I can do a PR if needed.

Best

**Comment by kmjonsson** [comment]
Oh, you are using the 20.02.2 branch. The error should not be there yes. I'm not sure that the 20.02.2 branch is needed anymore. I'll check and get back to you,.

**Comment by kmjonsson** [comment]
Use the master branch. I have pushed the latest version.
